spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-79oxl8wg.sql.tencentcdb.com:27891/test1
    username: root
    password: Happy008
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
mybatis:
  mapper-locations: classpath:mapperImpl/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true     # 开启驼峰原则，将数据库带下划线的字段自动转为驼峰原则的命名
server:
  port: 8999